apiVersion: v1
kind: Service
metadata:
  name: diary-service
  labels:
    app: diary-service
spec:
  selector:
    app: diary-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
  type: ClusterIP
  